FROM golang:1.26.2-alpine AS builder
WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o api .

FROM scratch
COPY --from=builder /app/api /api
ENTRYPOINT ["/api"]